networks:
  market:
    external:
      name: market

version: '2'

services:
  unique-market:
    container_name: uniq-market-client
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    networks:
      - market
    environment:
      - PORT=3000
    ports:
      - 3000:3000

  dafc-market:
    container_name: dafc-market-client
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./dafc/variables.css:/usr/share/nginx/html/variables.css:ro
    networks:
      - market
    environment:
      - PORT=3001
    ports:
      - 3001:3001
