version: '2'
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    container_name: uniq-market-client
    ports:
      - 3000:3000
    volumes:
      - ./src:/src
    command: yarn start